apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: test
spec:
  # identify Pods object (node deployment) to be controlled by service
  selector:
    # cannot "matchLabel" because this API is older
    app: second-app
    # don't need all labels, just need to be specific enough
    # tier: backend
  ports: # expose list of ports
    - protocol: 'TCP' # default is TCP
      port: 80 # from outside
      targetPort: 8080 # from container
    # can expose more than one port
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer # most common
