# need node to setup image although react doesn't need node
FROM node:14-alpine as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

# multi-stage build, use RUN
RUN npm run build
# CMD [ "npm", "run", "build" ]

# second stage, use another base image
FROM nginx:stable-alpine

# copy file from previous stage (given alias "build")
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]