apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: shawlu95/kube-data-demo:v4
          env:
            - name: STORY_FOLDER
              value: 'story'
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            # claim by metadata name
            claimName: host-pvc
