apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth # which pod to apply
  type: ClusterIP # should not be public-facing
  ports:
    - protocol: TCP
      port: 80 # container external
      targetPort: 80 # container internal
