apiVersion: v1
kind: Service
metadata:
  name: react-srv
spec:
  selector:
    app: react # which pod to apply
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000 # container external
      targetPort: 80 # container internal
