apiVersion: v1
kind: Service
metadata:
  name: users-srv
spec:
  selector:
    app: users # which pod to apply
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080 # container external
      targetPort: 8080 # container internal
