apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: shawlu95/kube-network-users:latest
          env:
            - name: AUTH_URL
              value: '10.109.186.22'
